/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RidesIndexRouteImport } from './routes/rides.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsTripCalculatorRouteImport } from './routes/tools.trip-calculator'
import { Route as ToolsItineraryBuilderRouteImport } from './routes/tools.itinerary-builder'
import { Route as RidesSlugRouteImport } from './routes/rides.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTripCalculatorRoute = ToolsTripCalculatorRouteImport.update({
  id: '/tools/trip-calculator',
  path: '/tools/trip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsItineraryBuilderRoute = ToolsItineraryBuilderRouteImport.update({
  id: '/tools/itinerary-builder',
  path: '/tools/itinerary-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesSlugRoute = RidesSlugRouteImport.update({
  id: '/rides/$slug',
  path: '/rides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/rides/': typeof RidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/rides': typeof RidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/rides/$slug': typeof RidesSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/rides/': typeof RidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/rides/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
    | '/blog/'
    | '/destinations/'
    | '/rides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/rides/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
    | '/blog'
    | '/destinations'
    | '/rides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/rides/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
    | '/blog/'
    | '/destinations/'
    | '/rides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  RidesSlugRoute: typeof RidesSlugRoute
  ToolsItineraryBuilderRoute: typeof ToolsItineraryBuilderRoute
  ToolsTripCalculatorRoute: typeof ToolsTripCalculatorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trip-calculator': {
      id: '/tools/trip-calculator'
      path: '/tools/trip-calculator'
      fullPath: '/tools/trip-calculator'
      preLoaderRoute: typeof ToolsTripCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/itinerary-builder': {
      id: '/tools/itinerary-builder'
      path: '/tools/itinerary-builder'
      fullPath: '/tools/itinerary-builder'
      preLoaderRoute: typeof ToolsItineraryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$slug': {
      id: '/rides/$slug'
      path: '/rides/$slug'
      fullPath: '/rides/$slug'
      preLoaderRoute: typeof RidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  RidesSlugRoute: RidesSlugRoute,
  ToolsItineraryBuilderRoute: ToolsItineraryBuilderRoute,
  ToolsTripCalculatorRoute: ToolsTripCalculatorRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
