/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsTripCalculatorRouteImport } from './routes/tools.trip-calculator'
import { Route as ToolsItineraryBuilderRouteImport } from './routes/tools.itinerary-builder'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTripCalculatorRoute = ToolsTripCalculatorRouteImport.update({
  id: '/tools/trip-calculator',
  path: '/tools/trip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsItineraryBuilderRoute = ToolsItineraryBuilderRouteImport.update({
  id: '/tools/itinerary-builder',
  path: '/tools/itinerary-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/destinations': typeof DestinationsRouteWithChildren
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/tools/itinerary-builder': typeof ToolsItineraryBuilderRoute
  '/tools/trip-calculator': typeof ToolsTripCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/destinations'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/destinations'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/destinations'
    | '/search'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/tools/itinerary-builder'
    | '/tools/trip-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  DestinationsRoute: typeof DestinationsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ToolsItineraryBuilderRoute: typeof ToolsItineraryBuilderRoute
  ToolsTripCalculatorRoute: typeof ToolsTripCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trip-calculator': {
      id: '/tools/trip-calculator'
      path: '/tools/trip-calculator'
      fullPath: '/tools/trip-calculator'
      preLoaderRoute: typeof ToolsTripCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/itinerary-builder': {
      id: '/tools/itinerary-builder'
      path: '/tools/itinerary-builder'
      fullPath: '/tools/itinerary-builder'
      preLoaderRoute: typeof ToolsItineraryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  DestinationsRoute: DestinationsRouteWithChildren,
  SearchRoute: SearchRoute,
  ToolsItineraryBuilderRoute: ToolsItineraryBuilderRoute,
  ToolsTripCalculatorRoute: ToolsTripCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
